### ISSUE TITLE
Unable to get property 'x' of undefined or null reference

### ISSUE THREAD

**Issue by it-ony** [Adyen/CSE-JS#53]
In our frontend error tracking tool, we see the following error 

```
Unable to get property 'x' of undefined or null reference
```

with the minimal stacktrace of 

```
at ? line 14, column 29192 (https://checkout.spreadshirt.fr/Public/Checkout2/build/2.38.7/checkout/lib/adyen.encrypt.nodom.min.js:14)
```

which drills down to the code block

```
t.accelerationIncludingGravity.x
```

Additional data:
* IE: 89% effected
* Edge: 11% effeced

**Comment by ArnoudAdyen** [comment]
Hi,

This is also fixed in the v0.1.20

**Comment by it-ony** [comment]
I like to reopen, this as it's not fixed or there is some problems with the tagging in this repository. 

I'm downloading dependency tagged with v0.1.20, but I can see the null pointer still in the logs. 

The problem might be that the tagged version, has a different version in the comment 
See https://raw.githubusercontent.com/Adyen/adyen-cse-web/v0.1.20/js/adyen.encrypt.nodom.min.js

```
/*
 *
 * Client Encryption of Forms.
 *
 * Includes: 
 * * RSA and ECC in JavaScript | http://www-cs-students.stanford.edu/~tjw/jsbn/
 * * Stanford Javascript Crypto Library | http://crypto.stanford.edu/sjcl/
 * * JSON in JavaScript | http://www.JSON.org/
 * 
 * Version: 0_1_19
 * Author:  ADYEN (c) 2014
 */
```
